### ISSUE TITLE
After upgrade to v1.0.11, compile to commonjs modules no longer possible in tsConfig

### ISSUE THREAD

**Issue by danrostron** [pixijs/layers#96]
I recently upgraded from Pixi v5 to v6 and also upgraded to pixi layers to 1.0.11 (compatible with v6). After a long time trying to figure out why I was receiving the ''renderer.incDisplayOrder is not a function" error, I realised that by changing my tsConfig.json module setting from "commonjs" to "ES6" it resolves the issue.

However this same change, now seems to cause a conflict with Robotlegs/Pixi which requires modules format to be common.js.

Why does Pixi layers require this, and is there anyway to resolve it?

**Comment by ivanpopelyshev** [comment]
Whast robotlegs?

**Comment by danrostron** [comment]
Yes, we've been using it for many years, but the dependencies are becoming increasingly hard to update to latest versions.

It's based on Inversify JS (which handles dependency injection) and it seems they require 'commonjs' modules - https://github.com/inversify/InversifyJS#-installation

Any ideas how I can get Pixi layers to play nicely with commonjs module format @ivanpopelyshev?

**Comment by danrostron** [comment]
Managed to instead get Robotlegs working using ES2015 module format instead.
